"""Sukurta DesignStyle ir TrainingLog lenteles

Revision ID: 21e464e8cb02
Revises: 
Create Date: 2026-04-08 09:32:49.545503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e464e8cb02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood_keyword', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('header_font', sa.String(length=100), nullable=False),
    sa.Column('body_font', sa.String(length=100), nullable=False),
    sa.Column('color_palette', sa.JSON(), nullable=False),
    sa.Column('color_histogram', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_styles_mood_keyword'), ['mood_keyword'], unique=False)

    op.create_table('training_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('input_type', sa.String(length=50), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_logs')
    with op.batch_alter_table('design_styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_styles_mood_keyword'))

    op.drop_table('design_styles')
    # ### end Alembic commands ###
